import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import MainProvider from "@/contexts/MainProvider";
import "./globals.css";
import "@near-wallet-selector/modal-ui/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  );
}
